# Назва програми (унікальна на Fly.io)
app = "codivag"

# Регіон, де буде запускатися контейнер (наприклад, Франкфурт)
primary_region = "fra"

# Побудова через Dockerfile
[build]
  dockerfile = "Dockerfile"

# Порт, який слухає контейнер (для Telegram Webhook, якщо знадобиться)
[env]
  # TOKEN передається через секрети, тому тут не обов'язково
  # BOT_TOKEN = "your_token_here"

# Вказуємо, що додаток постійно працює
[deploy]
  release_command = ""

# Автоматичне оновлення Fly.io
[experimental]
  auto_rollback = true
